import { useState } from "react";
import { X, ArrowLeft } from "lucide-react";
import { useAuth } from "../auth";
import { useLanguage } from "../i18n";
import { api } from "../api";
type Mode = "login" | "register" | "forgot" | "reset";
export function AuthModal({ onClose }: { onClose: () => void }) {
  const { login, register } = useAuth();
  const { t } = useLanguage();
  const [mode, setMode] = useState<Mode>("login");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);
  const [loginEmail, setLoginEmail] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  const [regName, setRegName] = useState("");
  const [regSurname, setRegSurname] = useState("");
  const [regCity, setRegCity] = useState("");
  const [regSchool, setRegSchool] = useState("");
  const [regGrade, setRegGrade] = useState("");
  const [regEmail, setRegEmail] = useState("");
  const [regPassword, setRegPassword] = useState("");
  const [forgotEmail, setForgotEmail] = useState("");
  const [resetCode, setResetCode] = useState("");
  const [resetPw, setResetPw] = useState("");
  const clear = () => { setError(""); setSuccess(""); };
  const sw = (m: Mode) => { clear(); setMode(m); };
  const handleLogin = async (e: React.FormEvent) => { e.preventDefault(); clear(); setLoading(true); try { await login(loginEmail, loginPassword); onClose(); } catch (err: any) { setError(err.message || "Error"); } finally { setLoading(false); } };
  const handleRegister = async (e: React.FormEvent) => { e.preventDefault(); clear(); setLoading(true); try { await register({ name: regName, surname: regSurname, email: regEmail, password: regPassword, city: regCity || undefined, school: regSchool || undefined, grade: regGrade || undefined }); onClose(); } catch (err: any) { setError(err.message || "Error"); } finally { setLoading(false); } };
  const handleForgot = async (e: React.FormEvent) => { e.preventDefault(); clear(); setLoading(true); try { await api.auth.forgotPassword(forgotEmail); setSuccess("Kod otpravlen"); setMode("reset"); } catch (err: any) { setError(err.message || "Error"); } finally { setLoading(false); } };
  const handleReset = async (e: React.FormEvent) => { e.preventDefault(); clear(); setLoading(true); try { await api.auth.resetPassword(forgotEmail, resetCode, resetPw); setSuccess("Parol izmenen"); setMode("login"); } catch (err: any) { setError(err.message || "Error"); } finally { setLoading(false); } };
  const inp = "w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm";
  const btn = "w-full py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 font-medium";
  return (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={onClose}><div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-full max-w-md mx-4 p-6" onClick={e => e.stopPropagation()}><div className="flex justify-between items-center mb-4"><div className="flex items-center gap-2">{(mode==="forgot"||mode==="reset")&&<button onClick={()=>sw("login")}><ArrowLeft className="w-5 h-5 text-gray-500"/></button>}<h2 className="text-xl font-bold text-gray-900 dark:text-white">{mode==="login"?t("nav.login"):mode==="register"?"Registratsiya":mode==="forgot"?"Zabyli parol?":"Novyy parol"}</h2></div><button onClick={onClose}><X className="w-5 h-5 text-gray-500"/></button></div>{error&&<div className="mb-3 p-3 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-lg text-sm">{error}</div>}{success&&<div className="mb-3 p-3 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 rounded-lg text-sm">{success}</div>}{mode==="login"&&(<form onSubmit={handleLogin} className="space-y-3"><input type="text" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} required placeholder="Login ili email" className={inp}/><input type="password" value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} required placeholder="Parol" className={inp}/><button type="button" onClick={()=>sw("forgot")} className="text-sm text-blue-600 hover:underline">Zabyli parol?</button><button type="submit" disabled={loading} className={btn}>{loading?"...":t("nav.login")}</button></form>)}{mode==="register"&&(<form onSubmit={handleRegister} className="space-y-3"><div className="grid grid-cols-2 gap-2"><input type="text" value={regName} onChange={e=>setRegName(e.target.value)} required placeholder="Imya" className={inp}/><input type="text" value={regSurname} onChange={e=>setRegSurname(e.target.value)} required placeholder="Familiya" className={inp}/></div><div className="grid grid-cols-3 gap-2"><input type="text" value={regCity} onChange={e=>setRegCity(e.target.value)} placeholder="Gorod" className={inp}/><input type="text" value={regSchool} onChange={e=>setRegSchool(e.target.value)} placeholder="Shkola" className={inp}/><input type="text" value={regGrade} onChange={e=>setRegGrade(e.target.value)} placeholder="Klass" className={inp}/></div><input type="email" value={regEmail} onChange={e=>setRegEmail(e.target.value)} required placeholder="Email" className={inp}/><input type="password" value={regPassword} onChange={e=>setRegPassword(e.target.value)} required placeholder="Parol (min 6)" minLength={6} className={inp}/><button type="submit" disabled={loading} className={btn}>{loading?"...":"Zaregistrirovatsya"}</button></form>)}{mode==="forgot"&&(<form onSubmit={handleForgot} className="space-y-3"><p className="text-sm text-gray-600 dark:text-gray-400">Vvedite email dlya polucheniya koda.</p><input type="email" value={forgotEmail} onChange={e=>setForgotEmail(e.target.value)} required placeholder="Email" className={inp}/><button type="submit" disabled={loading} className={btn}>{loading?"...":"Otpravit kod"}</button></form>)}{mode==="reset"&&(<form onSubmit={handleReset} className="space-y-3"><p className="text-sm text-gray-600 dark:text-gray-400">Vvedite kod i novyy parol.</p><input type="text" value={resetCode} onChange={e=>setResetCode(e.target.value.replace(/\D/g,"").slice(0,6))} required placeholder="000000" maxLength={6} className={inp+" text-center text-lg tracking-widest"}/><input type="password" value={resetPw} onChange={e=>setResetPw(e.target.value)} required placeholder="Novyy parol" minLength={6} className={inp}/><button type="submit" disabled={loading} className={btn}>{loading?"...":"Izmenit parol"}</button></form>)}{(mode==="login"||mode==="register")&&(<div className="mt-4 text-center text-sm text-gray-600 dark:text-gray-400">{mode==="login"?<span>Net akkaunta? <button onClick={()=>sw("register")} className="text-blue-600 hover:underline">Registratsiya</button></span>:<span>Est akkaunt? <button onClick={()=>sw("login")} className="text-blue-600 hover:underline">Voyti</button></span>}</div>)}</div></div>);
}
